name: 'Baidu Tieba Auto Sign In'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '5 8,14 * * *'

jobs:
  TieBa_Sign:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Set python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.9.12'
      - name: 'Install dependencies'
        run: python -m pip install --upgrade requests
      - name: 'Start Sign'
        env:
          BDUSS: ${{ secrets.BDUSS }}
        run: python main.py
